In [56]:
## 1 - Create an array from 0-9
import numpy as np 

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
## 2 - Create a 3×3 NumPy array of all Boolean value Trues
import numpy as np 
array = np.full((3,3), True, dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [62]:
## 3 - Extract all odd numbers from array of 1-10
import numpy as np

arr = np.arange(1,11)

odd = np.extract(arr%2== 1 , arr)
print(odd)

[1 3 5 7 9]


In [63]:
## 4 - Replace all odd numbers in an array of 1-10 with the value -1

import numpy as np

arr = np.arange(1,11)

new_arr = np.where(arr%2 == 1 , -1 , arr)
print(new_arr)



[-1  2 -1  4 -1  6 -1  8 -1 10]


In [64]:
## 5 - Convert a 1D array to a 2D array with 2 rows

import numpy as np

arr = np.arange(6)

new_arr = arr.reshape(2,3)

print(new_arr)

[[0 1 2]
 [3 4 5]]


In [23]:
## 6 - Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals

import numpy as np

arr1 = np.arange(15,30,2)
arr2 = np.arange(1,9)
np.vstack((arr1,arr2))  
np.dot(arr1,arr2)
arr = np.sum(arr)
print(arr)




876
